-- FUNCTION 1: TOTAL_DEBIT
CREATE OR REPLACE FUNCTION TOTAL_DEBIT(Code IN NUMBER)
RETURN NUMBER IS 
   debit NUMBER(10);
BEGIN
   IF Code IS NOT NULL AND Code > 0 THEN
      SELECT NVL(SUM(Salary), 0) INTO debit FROM Employees WHERE ID = Code;
   ELSE
      SELECT NVL(SUM(Salary), 0) INTO debit FROM Employees;
   END IF;
   RETURN debit;
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      RETURN 0;
   WHEN OTHERS THEN
      RAISE;
END;
/

-- Test Function 1
DECLARE 
  AMOUNT NUMBER(10);
BEGIN
  AMOUNT := TOTAL_DEBIT(5);
  DBMS_OUTPUT.PUT_LINE('Total Debit: ' || AMOUNT);
END;
/

-- FUNCTION 2: TOTAL_CREDIT
CREATE OR REPLACE FUNCTION TOTAL_CREDIT(Code IN NUMBER)
RETURN NUMBER IS 
   total_debit NUMBER(10);
   total_credit NUMBER(10);
BEGIN 
   total_debit := TOTAL_DEBIT(Code);
   total_credit := total_debit + 100000;
   RETURN total_credit;
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      RETURN 100000;
   WHEN OTHERS THEN
      RAISE;
END;
/

-- Test Function 2
DECLARE 
  PROFIT_AMOUNT NUMBER(10);
BEGIN
  PROFIT_AMOUNT := TOTAL_CREDIT(5);
  DBMS_OUTPUT.PUT_LINE('Total Credit: ' || PROFIT_AMOUNT);
END;
/

-- FUNCTION 3: TOTAL_PROFIT
CREATE OR REPLACE FUNCTION TOTAL_PROFIT(Code IN NUMBER)
RETURN NUMBER IS
    debit NUMBER(10);
    credit NUMBER(10);
    profit NUMBER(10);
BEGIN
    debit := TOTAL_DEBIT(Code);
    credit := TOTAL_CREDIT(Code);
    profit := credit - debit;
    RETURN profit;
EXCEPTION
   WHEN NO_DATA_FOUND THEN
      RETURN 0;
   WHEN OTHERS THEN
      RAISE;
END;
/

-- Test Function 3
DECLARE 
  PROFIT NUMBER(10);
BEGIN
  PROFIT := TOTAL_PROFIT(5);
  DBMS_OUTPUT.PUT_LINE('Total Profit: ' || PROFIT);
END;
/

-- FUNCTION 4: FIND_PLANE
CREATE OR REPLACE FUNCTION FIND_PLANE(FLIGHT IN NUMBER, TIME_VAL IN NUMBER)
RETURN VARCHAR2 IS 
   loc VARCHAR2(50);
BEGIN
   SELECT Place INTO loc 
   FROM Location
   WHERE (Flight_No = FLIGHT) AND (TIME_VAL >= Start_Time) AND (TIME_VAL <= End_Time);
   RETURN loc;
EXCEPTION
   WHEN NO_DATA_FOUND THEN 
      RETURN 'Not Found';
   WHEN OTHERS THEN
      RAISE; 
END;
/

-- Test Function 4
DECLARE 
  locations VARCHAR2(50);
BEGIN
  locations := FIND_PLANE(15, 5.1);
  DBMS_OUTPUT.PUT_LINE('Location: ' || locations);
END;
/