CREATE OR REPLACE PROCEDURE FIND_PLANE(
   FLIGHT IN NUMBER,
   TIME_VAL IN NUMBER,
   LOC OUT VARCHAR2
)
IS 
BEGIN
   SELECT Place INTO LOC 
   FROM Location
   WHERE (Flight_No = FLIGHT) AND (TIME_VAL >= Start_Time) AND (TIME_VAL <= End_Time);
EXCEPTION
   WHEN NO_DATA_FOUND THEN 
      LOC := 'Not Found';
   WHEN OTHERS THEN
      RAISE; 
END;
/

-- Test Procedure
DECLARE
   V_LOC VARCHAR2(50);
BEGIN
   FIND_PLANE(15, 5.1, V_LOC);
   DBMS_OUTPUT.PUT_LINE('Plane location: ' || V_LOC);
END;
/